/*
 * Copyright (c) 2026 by Christian Kellner.
 * Licensed under Apache-2.0 with Commons Clause and Attribution/Naming Clause
 */

export const TRACKING_POIS = {
  DISTANCE_ADDRESS_ENTERED: 'DISTANCE_ADDRESS_ENTERED',
  WELCOME_FINISHED: 'WELCOME_FINISHED',
  WELCOME_SKIPPED: 'WELCOME_SKIPPED',
  JOBS_TABLE_VIEW: 'JOBS_TABLE_VIEW',
  LISTING_TABLE_VIEW: 'LISTING_TABLE_VIEW',
  BASE_URL_SETTING: 'BASE_URL_SETTING',
  SET_PROXY_SETTING: 'SET_PROXY_SETTING',
  DETECTED_AS_BOT: 'DETECTED_AS_BOT',
  NOTES_CREATE: 'NOTES_CREATE',
  USING_LISTING_STATUS: 'USING_LISTING_STATUS',
};
