name: Close stale PRs

on:
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity.'
          close-pr-message: 'Closing this PR due to prolonged inactivity.'
          exempt-pr-labels: 'keep-open'
          only: 'pulls'
