name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'yarn'

      - run: yarn install
      - run: yarn test:offline
